### PR TITLE
migrate from PHPExcel to PhpSpreadsheet

### PR DESCRIPTION
**Pull request by MDevster**

### CODE REVIEW

**Comment by MDevster** [comment]
fixes #58

**Comment by zonky2** [comment]
added with https://github.com/terminal42/contao-leads/commit/432c96131b2848c9e46a4541c38ef501938513d7

**Comment by aschempp** [comment]
Looks like this was not fully merged, at least the composer.json is not update? And not sure about the other changes suggested here? @richardhj can you check this?

**Comment by aschempp** [comment]
Also see https://github.com/terminal42/contao-leads/issues/58

**Comment by richardhj** [comment]
PR is outdated and compatibility with php-spreadsheet already given.

**Comment by aschempp** [comment]
But not everything from this PR has been merged? E.g. the `suggest` in `composer.json` is still wrong?

**Pull request closed without merging**
