### PR TITLE
Hotfix record description

### PR DESCRIPTION
**Pull request by zonky2**
change the description like the french version

it creates confusion without explanation since the simple tokens in NC have a prefix `form_`...

### CODE REVIEW

**Comment by Toflar** [comment]
Can we use `back end` (and `Backend` in German) instead of `BE`)

**Comment by zonky2** [comment]
and in french?

**Comment by Toflar** [comment]
We just leave that until somebody wants to improve it :)

**Comment by zonky2** [comment]
ok

**Pull request merged**
